#!/bin/bash
#
# vim: set ts=4 sw=4 tw=0 et :
#
# Copyright (C) 2014-2017, University of Washington. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
# list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
# may be used to endorse or promote products derived from this software without
# specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# This script is based on https://gist.github.com/leucos/6f8d93de3493431acd29
#

# Change defaults below
# ---------------------

# This is a temp inventory generated to start the DO droplets
# You might want to change ansible_python_interpreter
LOCALHOST_ENTRY="localhost ansible_python_interpreter='/usr/bin/env python'"

function bail_out {
  echo $1
  echo -e "Usage: $0 <inventory_directory>\n"
  echo -e "\tinventory_directory: the directory containing the inventory goal (compulsory)"
  exit 1
}

# Check that inventory is a directory
# We need this since we generate a complementary inventory with IP addresses for hosts
INVENTORY=$1
[[ ! -d "$INVENTORY" ]]  && bail_out "Inventory does not exist, is not a directory, or is not set"
INVENTORY_GENERATED=${INVENTORY}/nodes-generated.yml

# Get a list of hosts from inventory dir
HOSTS=$(ansible -i $1/hosts --list-hosts all | awk '/^    / { print $1 }' | tr '\n' ' ' 2>/dev/null)

# Clean up previously generated inventory
cat <<EOD > ${INVENTORY_GENERATED}
---
# This is a generated inventory file produced by $0.
# DO NOT EDIT THIS FILE.

do:
  hosts:
EOD

# Creating temporary inventory with only localhost in it
TEMP_INVENTORY=$(mktemp)
# Cleanup on exit
trap "rm -f ${TEMP_INVENTORY}" EXIT SIGHUP SIGINT SIGQUIT SIGTERM
echo "[+] Creating temporary inventory in ${TEMP_INVENTORY}"
echo ${LOCALHOST_ENTRY} > ${TEMP_INVENTORY}

# Create inventory for running droplets
for i in ${HOSTS}; do
  IP=$(ansible localhost \
         -c local \
         -i $TEMP_INVENTORY \
         -m digital_ocean \
         -a "state=present command=droplet unique_name=yes name=$i" |\
       tee -a do_post.log |\
       sed 's/localhost | SUCCESS =>//' |\
       jq -C '.droplet.ip_address' 2>/dev/null |\
       cut -f2 -d'"')
  [[ ! -z $IP ]] && echo -e "    '$i':\n      ansible_host: $IP" >> ${INVENTORY_GENERATED}
done

exit 0
